FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/master ./cmd/master

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/master /bin/master
COPY configs/master.yaml /etc/omnihive/master.yaml

EXPOSE 8080
ENTRYPOINT ["/bin/master", "-config", "/etc/omnihive/master.yaml"]
