FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/simulator ./cmd/simulator


FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/simulator /bin/simulator
COPY configs/simulator.yaml /etc/omnihive/simulator.yaml

ENTRYPOINT ["/bin/simulator", "-config", "/etc/omnihive/simulator.yaml"]
